"""add_is_system_to_deck_nullable_owner

Revision ID: d83e8efcb0c1
Revises: ad8c2750f6bb
Create Date: 2026-04-20 13:31:30.050548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd83e8efcb0c1'
down_revision: Union[str, None] = 'ad8c2750f6bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('is_system', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('decks', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('decks', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('decks', 'is_system')
    # ### end Alembic commands ###
